export const SELLER_LIST_REQUEST = "SELLER_LIST_REQUEST";
export const SELLER_LIST_SUCCESS = "SELLER_LIST_SUCCESS";
export const SELLER_LIST_FAIL = "SELLER_LIST_FAIL";

export const SELLER_LOGIN_REQUEST = "SELLER_LOGIN_REQUEST";
export const SELLER_LOGIN_SUCCESS = "SELLER_LOGIN_SUCCESS";
export const SELLER_LOGIN_FAIL = "SELLER_LOGIN_FAIL";
export const SELLER_LOGOUT = "SELLER_LOGOUT";

export const SELLER_REGISTER_REQUEST = "SELLER_REGISTER_REQUEST";
export const SELLER_REGISTER_SUCCESS = "SELLER_REGISTER_SUCCESS";
export const SELLER_REGISTER_FAIL = "SELLER_REGISTER_FAIL";

export const SELLER_VIEW_REQUEST = "SELLER_VIEW_REQUEST";
export const SELLER_VIEW_SUCCESS = "SELLER_VIEW_SUCCESS";
export const SELLER_VIEW_FAIL = "SELLER_VIEW_FAIL";

export const SELLER_UPDATE_REQUEST = "SELLER_UPDATE_REQUEST";
export const SELLER_UPDATE_SUCCESS = "SELLER_UPDATE_SUCCESS";
export const SELLER_UPDATE_FAIL = "SELLER_UPDATE_FAIL";

export const SELLER_DELETE_REQUEST = "SELLER_DELETE_REQUEST";
export const SELLER_DELETE_SUCCESS = "SELLER_DELETE_SUCCESS";
export const SELLER_DELETE_FAIL = "SELLER_DELETE_FAIL";

export const SELLER_VIEW_BY_ID_REQUEST = "SELLER_VIEW_BY_ID_REQUEST";
export const SELLER_VIEW_BY_ID_SUCCESS = "SELLER_VIEW_BY_ID_SUCCESS";
export const SELLER_VIEW_BY_ID_FAIL = "SELLER_VIEW_BY_ID_FAIL";

export const SELLER_UPDATE_BY_ID_REQUEST = "SELLER_UPDATE_BY_ID_REQUEST";
export const SELLER_UPDATE_BY_ID_SUCCESS = "SELLER_UPDATE_BY_ID_SUCCESS";
export const SELLER_UPDATE_BY_ID_FAIL = "SELLER_UPDATE_BY_ID_FAIL";
